[general]
description = "Voxel Space render engine in Ada"
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]

project-files = ["ada_voxel.gpr"]
executables = ["main"]

licenses = ["MIT"]

["0.0.0"]
origin = "file://.."
["0.0.0".depends-on]
sdlada = "^2.3.1"

